# -*- coding: utf-8 -*-
"""Readme.8md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tX9RRS8mmVBSixUeL5t23cJWe76XkVh
"""



"""Conclusion: Depth-First Search is a graph traversal algorithm that explores a graph by going as deep as possible before backtracking. It is useful for path finding, graph traversal, cycle detection, and connectivity checking."""